### ISSUE TITLE
error in thaum converter or mana display

### ISSUE THREAD

**Issue by LucidCrux** [fuzzything44/Incremental#3]
I had 1 mana, turned on 1 converter then turned it off, then I had 3 mana. I think it might just be visual. If I turn a single converter on again it takes away all three.

**Comment by fuzzything44** [comment]
I can't reproduce this. Converters should take 3 mana to run, are you sure you only had 1 total mana?

**Comment by LucidCrux** [comment]
Ahh, that was the issue. It turned off greed, which I didn't notice. You probably need to include mana cost in the converter tooltip then.

**Comment by fuzzything44** [comment]
Added in next update.
