### ISSUE TITLE
Greed doubles maintenance cost as well.

### ISSUE THREAD

**Issue by freitagdavid** [fuzzything44/Incremental#4]
When you enable greed it seems to also double the cost of running many of the buildings. Not sure if this is a bug or a feature.

**Comment by fuzzything44** [comment]
Uses 2 mana, but doubles net money and gold gains.

The keyword is net. Working as intended.

**Comment by freitagdavid** [comment]
Oh okay. That makes sense. Keep up the good work game is pretty interesting so far.
