### ISSUE TITLE
Sandcastle upgrade pricing

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [fuzzything44/Incremental#6]
The price for the sandcastle upgrade is not reset upon prestiging, even though the number of sandcastles goes to zero. According to the provided formula on the Wiki, the price for the upgrade is 1m + 1m*(n sandcastles). So at the early stage of the game the price should be 1m, but instead was 15m.
<img width="803" alt="sandcastles" src="https://user-images.githubusercontent.com/31759736/33275781-e4577a32-d350-11e7-8cc7-e7387a3403fd.PNG">

**Comment by fuzzything44** [comment]
Working as intended. It's only free prestige value every ONG you get. Also, even normally it definitely isn't 1m + 1m * number of sandcastles - a logikitten reward resets the price.
