### ISSUE TITLE
Technomancy pegging CPU in Chrome

### ISSUE THREAD

**Issue by OneGeek** [fuzzything44/Incremental#7]
To reproduce:
Visit https://fuzzything44.github.io/Incremental/Technomancy/ and view the Chrome task manager (shift-esc). Notice that the tab is using around 100% of the cpu. I suggest increasing the interval for update from 35ms to at least 1/4 second. The chrome profiler is showing me that update takes ~50ms to run on my machine. Also I'm very early on in the game.

**Comment by fuzzything44** [comment]
Weird, I'm getting update running much quicker - only about 12-17ms per loop. Next update will reduce the interval to 50ms though.
